po3/contact/forms.py
from flask_wtf import Form
from wtforms import TextField, TextAreaField, SubmitField
from wtforms import ValidationError
from wtforms.validators import DataRequired, Email
 
class ContactForm(Form):
  name = TextField('Name',validators=[DataRequired()])
  email = TextField('Email',validators=[DataRequired(),Email()])
  subject = TextField('Subject',validators=[DataRequired()])
  message = TextAreaField('Message',validators=[DataRequired()])
  submit = SubmitField("Send")

po3/recipe_cards/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField,FileField
from wtforms.validators import DataRequired


class RecipeForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    description = TextAreaField('Description',validators=[DataRequired()])
    ingriedient1 = StringField('Ingridient 1 of 3',validators=[DataRequired()])
    ingriedient2 = StringField('Ingridient 2 of 3',validators=[DataRequired()])
    ingriedient3 = StringField('Ingridient 3 of 3',validators=[DataRequired()])
    smoothie_video = StringField('Smoothie',validators=[DataRequired()])
    submit = SubmitField('Post')

    

    

po3/contact/views.py
from flask import render_template,request,Blueprint,flash
from po3.contact.forms import ContactForm
from flask_mail import Message, Mail
from po3 import mail

contact = Blueprint('contact',__name__)

@contact.route('/contact', methods=['GET', 'POST'])
def contactme():
  form = ContactForm()
 
  if request.method == 'POST':
    if form.validate() == False:
      flash('All fields are required.')
      return render_template('contact.html', form=form)
    else:
      msg = Message(form.subject.data, sender='contact@example.com', recipients=['powerof333@yahoo.com'])
      msg.body = """
      From: %s &lt;%s&gt;
      %s
      """ % (form.name.data, form.email.data, form.message.data)
      mail.send(msg)
 
      return render_template('contact.html', success=True)
 
  elif request.method == 'GET':
    return render_template('contact.html', form=form)

po3/core/views.py
from po3.models import Recipe
from flask import render_template,Blueprint,request,url_for

core = Blueprint('core',__name__)


@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    recipe_cards = Recipe.query.order_by(Recipe.date.desc()).paginate(page=page,per_page=3)
    return render_template('index.html',recipe_cards=recipe_cards)

@core.route('/about')
def about():
    return render_template('about.html')

@core.route('/all_recipes.html')
def all_recipes():
    page = request.args.get('page',1,type=int)
    recipe_cards = Recipe.query.order_by(Recipe.date.desc()).paginate(page=page,per_page=9)
    return render_template('all_recipes.html',recipe_cards=recipe_cards)

po3/recipe_cards/views.py
from flask import render_template,url_for,flash,request,redirect,Blueprint,abort
from flask_login import current_user,login_required
from po3 import db
from po3.models import Recipe
from po3.recipe_cards.forms import RecipeForm

recipe_cards = Blueprint('recipe_cards',__name__)

# Create recipe card

@recipe_cards.route('/add_recipe',methods=['GET','POST'])
@login_required
def add_recipe():
    form = RecipeForm()

    if form.validate_on_submit():

        recipe_card = Recipe(title=form.title.data,
                            description=form.description.data,
                            ingriedient1=form.ingriedient1.data,
                            ingriedient2=form.ingriedient2.data,
                            ingriedient3=form.ingriedient3.data,
                            smoothie_video=form.smoothie_video.data,
                            user_id=current_user.id)

        db.session.add(recipe_card)
        db.session.commit()
        flash('Recipe Card created')
        return redirect(url_for('core.index'))
    
    return render_template('add_recipe.html',form=form)

# View recipe

@recipe_cards.route('/<int:recipe_card_id>')
def recipe_card(recipe_card_id):
    recipe_card = Recipe.query.get_or_404(recipe_card_id)
    return render_template('recipe_card.html',title=recipe_card.title,
                            date=recipe_card.date,recipe=recipe_card
    )

# Edit recipe

@recipe_cards.route("/<int:recipe_card_id>/edit_recipe",methods=['GET','POST'])
@login_required
def edit_recipe(recipe_card_id):
    recipe_card = Recipe.query.get_or_404(recipe_card_id)

    if recipe_card.chef != current_user:
        abort(403)

    form = RecipeForm()

    if form.validate_on_submit():

        recipe_card.title = form.title.data
        recipe_card.description = form.description.data
        recipe_card.ingriedient1 = form.ingriedient1.data
        recipe_card.ingriedient2 = form.ingriedient2.data
        recipe_card.ingriedient3 = form.ingriedient3.data
        recipe_card.smoothie_video = form.smoothie_video.data
        recipe_card.user_id = current_user.id

        db.session.commit()
        flash('Recipe Card updated')
        return redirect(url_for('recipe_cards.recipe_card',recipe_card_id=recipe_card.id))
    
    elif request.method == 'GET':
        form.title.data = recipe_card.title
        form.description.data = recipe_card.description
        form.ingriedient1.data = recipe_card.ingriedient1
        form.ingriedient2.data = recipe_card.ingriedient2
        form.ingriedient3.data = recipe_card.ingriedient3
        form.smoothie_video.data = recipe_card.smoothie_video

    return render_template('add_recipe.html',title='Editing',form=form)


@recipe_cards.route('/<int:recipe_card_id>/delete_recipe',methods=['GET','POST'])
@login_required
def delete_recipe(recipe_card_id):
    recipe_card = Recipe.query.get_or_404(recipe_card_id)
    if recipe_card.chef != current_user:
        abort(403)

    db.session.delete(recipe_card)
    db.session.commit()
    flash('Recipe deleted')
    return redirect(url_for('core.index'))

po3/users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user,current_user,logout_user,login_required
from po3 import db
from po3.models import User,Recipe
from po3.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from po3.picture_handler import add_profile_pic

users = Blueprint('users',__name__)

@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    first_name=form.first_name.data,
                    last_name=form.last_name.data,
                    password=form.password.data)
                    
        db.session.add(user)
        db.session.commit()
        flash("Account created!")
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)


@users.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()
        
        #if user.check_password(form.password.data) and user is not None:
        if user is not None and user.check_password(form.password.data):

            login_user(user)
            flash('Log in success!')

            next = request.args.get('next')
            if next == None or not next [0]=='/':
                next = url_for('core.index')
            return redirect(next)

    return render_template('login.html',form=form)





@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))




@users.route('/account',methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.profile_image.data:
            username = current_user.username
            pic = add_profile_pic(form.profile_image.data,username)
            current_user.profile_image = pic

        current_user.short_story = form.short_story.data
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User account updated')
        return redirect(url_for('users.account'))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    
    profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)

@users.route('/<username>')
def user_recipes(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    recipe_cards = Recipe.query.filter_by(chef=user).order_by(Recipe.date.desc()).paginate(page=page,per_page=10)
    return render_template('user_recipes.html',recipe_cards=recipe_cards,user=user)

po3/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <div class="container justify-content-center clean-block about-us">
        <div class="block-heading text-center pt-5">
            <h2 class="block-heading_title text-uppercase">our story</h2>
            <p class="block-heading_text">Our story began in 2019 when we noticed that smoothies became a great part of our morning routines. We were looking for inspiration in all kinds of blogs, websites, video channels, etc. bookmarking everything. After a while, there were so many recipes, bookmarks that it was hard to find anything. You know that feeling when you are thinking about that wonderful recipe which you tried yesterday and loved it but forgot where you found it. So this feeling inspired us to create Po3, a sharing platform, that all your favorite recipes could be stored in one place.

                We love smoothies and all the benefits that come with drinking them, we like mixing and blending different flavors. We enjoy experimenting with colors, tastes, and textures and encourage you to try it as well. We hope that you will enjoy being part of our community.
                
                Let’s get creative and start blending your vitamines! And the best part is, it's just 3 ingriedient's that will rock your day.</p>
        </div>
        <div class="row justify-content-center">
            <div class="col-sm-6 col-lg-4">
                <div class="card clean-card text-center"><img class="card-img-top w-100 d-block" src="{{url_for('static',filename='img/founder.jpg')}}" />
                    <div class="card-body info">
                        <h4 class="card-title">Rimvydas Česonis </h4>
                        <p class="card-text">Main chef and founder of po3.</p>
                        <div class="icons"><a href="https://www.facebook.com/rimvydas.cesonis" target="_blank"><i class="lab la-facebook"></i></a><a href="https://www.instagram.com/rimvydascesonis/" target="_blank"><i class="lab la-instagram"></i></a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

po3/templates/add_recipe.html
{% extends 'base.html' %}
{% block content %}

    <section class="jumbotron justify-content-center text-center">
        <div class="container">
        <h1>Welcome to our smoothies labaratory</h1>
        <p class="lead text-muted">Gather, create and share all your favourite smoothie recipes in one place</p>
        <p>
            <a href="{{url_for('users.register')}}" class="btn join-btn my-2">JOIN OUR COMMUNITY</a>
        </p>
        </div>
    </section>
    <section class="jumbotron justify-content-center text-center">
        <div class="container">
            <h1 class="pb-5">Welcome to our smoothies labaratory</h1>
            <form method="POST">
                    {{form.hidden_tag()}}
                <div class="col-sm-3 col-md-6 col-lg-4 mx-auto">
                    <div class="form-group">
                        {{form.title(class_="form-control",placeholder="Enter your recipe title")}}
                    </div>
                </div>
                <div class="col-sm-3 col-md-6 col-lg-4 mx-auto">
                    <div class="form-group">
                        {{form.ingriedient1(class_="form-control",placeholder="What is the first ingriedient?")}}
                    </div>
                </div>
                <div class="col-sm-3 col-md-6 col-lg-4 mx-auto">
                    <div class="form-group">
                        {{form.ingriedient2(class_="form-control",placeholder="What is the second ingriedient?")}}
                    </div>
                </div>
                <div class="col-sm-3 col-md-6 col-lg-4 mx-auto">
                    <div class="form-group">
                        {{form.ingriedient3(class_="form-control",placeholder="What is the special ingriedient?")}}
                    </div>
                </div>
                <div class="col-sm-3 col-md-6 col-lg-4 mx-auto">
                    <div class="form-group">
                        {{form.description(class_="form-control",placeholder="What is the special process in creating magic?")}}
                    </div>
                </div>
                <div class="col-sm-3 col-md-6 col-lg-4 mx-auto">
                    <div class="form-group">
                        {{form.smoothie_video(class_="form-control",placeholder="Enter smoothie youtube video")}}
                        <small class="form-text text-muted">Enter embed link example: "https://www.youtube.com/embed/xcJtL7QggTI"  </small>
                    </div>
                </div>
                <button type="submit" class="btn btn-link pt-5">
                    {{form.submit()}}
                </button>
              </form>        
        </div>
      </section>
{% endblock %}

po3/templates/all_recipes.html
{% extends 'base.html' %}
{% block content %}
<section class="jumbotron justify-content-center text-center">
    <div class="container">
      <h1>Welcome to our smoothies labaratory</h1>
      <p class="lead text-muted">Gather, create and share all your favourite smoothie recipes in one place</p>
      <p>
        <a href="{{url_for('users.register')}}" class="btn join-btn my-2">JOIN OUR COMMUNITY</a>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for recipe in recipe_cards.items %}
      <!--Single recipe-->
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <iframe width="100%" height="225" src="{{recipe.smoothie_video}}"></iframe>
            <div class="card-body">
              <h5 class="card-title">{{recipe.title}}</h5>
              <p class="card-text">{{recipe.description|truncate(50)}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{{url_for('recipe_cards.recipe_card',recipe_card_id=recipe.id)}}">Read More</a></button>
                </div>
                <small class="text-muted">Made by: <a href="{{url_for('users.user_recipes',username=recipe.chef.username)}}">{{recipe.chef.first_name}}</a></small>
                <small class="text-muted">{{recipe.date.strftime('%d-%m-%Y')}}</small>
              </div>
            </div>
          </div>
        </div>
      <!-- End of single recipe-->
        {% endfor %}
      </div>
    </div>
  </div>
  <section>
      <nav aria-label="Page navigation example" class="d-xl-flex justify-content-center pb-5">
        <ul class="pagination">
        {% for page_number in recipe_cards.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if recipe_cards.page == page_number %}
          <li class="page-item">
            <a class="page-link" href="{{url_for('core.all_recipes', page=page_number)}}">{{page_number}}</a>
          </li>
          {% else %}
          <li class="page-item">
            <a class="page-link" href="{{url_for('core.all_recipes', page=page_number)}}">{{page_number}}</a>
          </li>
          {% endif %}
        {% endfor %}
        </ul>
      </nav>
  </section>
{% endblock %}

po3/templates/base.html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Power of 3</title>
    <link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static', filename='img/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static', filename='img/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static', filename='img/favicon-16x16.png')}}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar" class="active"> <!-- class="active" for unexpanded sidebar-->
            <div class="sidebar-header">
                <img src="{{ url_for('static',filename='img/logo.svg') }}">
            </div>
            <div class="profile-picture text-center">
                {% if current_user.is_authenticated %}
                <img src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}">
                {% else %}
                <img src="{{url_for('static',filename='profile_pics/default.svg')}}">
                {% endif %}
            </div>
            <ul class="list-unstyled components">
                <div class="text-center"><img class="profile-pic">
                    <span class="text-capitalize">
                        <a class="text-uppercase" href="{{url_for('users.account')}}">account</a>
                    </span>                             
                </div>
                <li>
                    <a class="text-uppercase" href="{{url_for('core.index')}}">home</a>
                </li>
                <li>
                    <a class="text-uppercase" href="{{url_for('core.about')}}">about</a>
                </li>
                <li>
                    <a class="text-uppercase" href="{{url_for('core.all_recipes')}}">browse</a>
                </li>
                    
                {% if current_user.is_authenticated %}
                <li>
                    <a class="text-uppercase" href="{{url_for('recipe_cards.add_recipe')}}">add</a>
                </li>
                {% endif %}
                <li>
                    <a class="text-uppercase" href="{{url_for('contact.contactme')}}">contact</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.logout')}}">Log out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="recipes">

            <nav class="navbar navbar-expand bg-light">
                <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="btn">
                        <i class="las la-bars"></i>
                    </button>
                </div>
            </nav>
            {% block content %}

            {% endblock %}  
        </div>
    </div>
    <footer id="footerpad">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-8 mx-auto">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item"><a href="https://www.facebook.com/rimvydas.cesonis" target="_blank"><i class="lab la-facebook icons"></i></a></li>
                        <li class="list-inline-item"><a href="https://www.instagram.com/rimvydascesonis/" target="_blank"><i class="lab la-instagram icons"></i></a></li>
                    </ul><p class="copyright text-muted text-center">Copyright &copy; Po3 2020 | Simple is perfect</p></div>
            </div>
        </div>
    </footer>   
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>
</html>

po3/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<section class="jumbotron justify-content-center text-center">
    <div class="container">
        <h1 class="pb-5">Welcome to our smoothies labaratory</h1>
        {% if success %}
        <div class="col-sm-3 col-md-6 col-lg-4 mx-auto">
            <p>Thank you for your message. We'll get back to you shortly.</p>
        </div>
    </section>
        {% else %}
        <form action="{{url_for('contact.contactme')}}" method="POST">
                    {{form.hidden_tag()}}
            <div class="col-sm-3 col-md-6 col-lg-4 mx-auto">
                <div class="form-group">
                    {{form.name(class_="form-control",placeholder="Enter your name")}}
                </div>
            </div>
            <div class="col-sm-3 col-md-6 col-lg-4 mx-auto">
                <div class="form-group">
                    {{form.email(class_="form-control",placeholder="Enter email")}}
                    <small class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
            </div>
            <div class="col-sm-3 col-md-6 col-lg-4 mx-auto">
                <div class="form-group">
                    {{form.subject(class_="form-control",placeholder="Enter subject you like to discuss")}}
                </div>
            </div>
            <div class="col-sm-3 col-md-6 col-lg-4 mx-auto">
                <div class="form-group">
                    {{form.message(class_="form-control",placeholder="Tell us what's in your mind...")}}
                </div>
            </div>
            <button type="submit" class="btn btn-link pt-5">
                {{form.submit()}}
            </button>
          </form>        
    </div>
  </section>
{% endif %}
{% endblock %}

po3/templates/delete_recipe.html
{% extends 'base.html' %}
{% block content %}
{% endblock %}

po3/templates/index.html
{% extends 'base.html' %}

{% block content %}
<section class="jumbotron justify-content-center text-center">
    <div class="container">
      <h1 class="front-heading pb-3">Welcome to our smoothies labaratory</h1>
      <h2 class="front-heading_small pb-5">Gather, create and share all your favourite smoothie recipes in one place</h2>
      <p class="pb-5">
        <a href="{{url_for('users.register')}}" class="btn join-btn">JOIN OUR COMMUNITY</a>
      </p>
    </div>
  </section>
<div class="intersection"></div>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row justify-content-center">
        <h3 class="text-uppercase my-5 latest">latest recipes</h3>
      </div>
      <div class="row">
        {% for recipe in recipe_cards.items %}
      <!--Single recipe-->
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <iframe width="100%" height="225" src="{{recipe.smoothie_video}}"></iframe>
            <div class="card-body">
              <h5 class="card-title">{{recipe.title}}</h5>
              <p class="card-text">{{recipe.description|truncate(50)}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn join-btn view-recipe-btn"><a href="{{url_for('recipe_cards.recipe_card',recipe_card_id=recipe.id)}}">View Recipe</a></button>
                </div>
                <small class="text-muted">Made by: <a class="author-color" href="{{url_for('users.user_recipes',username=recipe.chef.username)}}">{{recipe.chef.first_name}}</a></small>
                <small class="text-muted">{{recipe.date.strftime('%d-%m-%Y')}}</small>
              </div>
            </div>
          </div>
        </div>
      <!-- End of single recipe-->
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row justify-content-center">
      <p class="pb-5">
        <a href="{{url_for('core.all_recipes')}}" class="btn join-btn all_recipe-btn text-uppercase">more recipes</a>
      </p>
    </div>
  </div>
<section>
  <div class="container">
    <div class="row mb-4">
      <div class="col-lg-6 col-md-4 mx-auto">
        <img class="smoothie_photo img-fluid" src="{{url_for('static', filename='img/smoothie_photo.png')}}" alt="">
      </div>
      <div class="col-lg-6 col-md-4 mx-auto text-center">
        <h4 class="text-uppercase pt-3">some facts why smoothies <br> are good for you</h4>
        <h5 class="text-uppercase pt-5">prevents dehydration</h5>
        <p class="pt-2">Water is the most abundant thing both on earth and in your body.
          About 70 percent of your body is water. Having smoothies along
          with breakfast is a great way to replenish the loss of water
          in your body during the summer.</p>
        <h5 class="text-uppercase pt-5">enhances immunity</h5>
        <p class="pt-2">Immunity refers to the ability of your body to fight against pathogens
          and diseases. This natural potential becomes degenerated due to several
          reasons. Interestingly, having smoothies made of ingredients that include
          nutrients like beta-carotene helps boost your immune system.</p>
        <h5 class="text-uppercase pt-5">improves skin</h5>
        <p class="pt-2">As you may know, food containing carotenoids, like mango and pumpkin,
          are highly beneficial for skin and complexion. Therefore, smoothies that
          contain these ingredients help you keep glowing in the summer.</p>
      </div>
    </div>
  </div>
</section>
{% endblock %}

po3/templates/recipe_card.html
{% extends 'base.html' %}
{% block content %}
  <section class="jumbotron justify-content-center text-center">
    <div class="container">
      <h1>Welcome to our smoothies labaratory</h1>
      <p class="lead text-muted">Gather, create and share all your favourite smoothie recipes in one place</p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
  <div class="card mx-auto" style="width: 28rem;">
    <iframe width="100%" height="225" src="{{recipe.smoothie_video}}"></iframe>
    <div class="card-body">
      <h5 class="card-title">{{recipe.title}}</h5>
      <p class="card-text">{{recipe.description}}</p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">{{recipe.ingriedient1}}</li>
      <li class="list-group-item">{{recipe.ingriedient2}}</li>
      <li class="list-group-item">{{recipe.ingriedient3}}</li>
    </ul>
    {% if recipe.chef == current_user %}
    <div class="card-body">
      <button type="button" class="btn btn-primary">
        <a href="{{ url_for('recipe_cards.edit_recipe', recipe_card_id=recipe.id) }}" class="card-link">Edit</a>
      </button>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteModal">
        Delete
      </button>
    </div>
    {% endif %}
  </div>
</div>
</div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete this recipe</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{ url_for('recipe_cards.delete_recipe', recipe_card_id=recipe.id) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

po3/templates/user_recipes.html
{% extends 'base.html' %}
{% block content %}
    <section class="jumbotron justify-content-center text-center">
        <div class="container">
        <h1>Welcome to our smoothies labaratory</h1>
            <p class="lead text-muted">Gather, create and share all your favourite smoothie recipes in one place</p>
            <p>
        <a href="{{url_for('users.register')}}" class="btn btn-primary my-2">JOIN OUR COMMUNITY</a>
        </p>
        </div>
    </section>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
{% for recipe in recipe_cards.items %}
      <!--Single recipe-->
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <iframe width="100%" height="225" src="{{recipe.smoothie_video}}"></iframe>
            <div class="card-body">
              <h5 class="card-title">{{recipe.title}}</h5>
              <p class="card-text">{{recipe.description|truncate(50)}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{{url_for('recipe_cards.recipe_card',recipe_card_id=recipe.id)}}">Read More</a></button>
                </div>
                <small class="text-muted">Made by: <a href="{{url_for('users.user_recipes',username=recipe.chef.username)}}">{{recipe.chef.first_name}}</a></small>
                <small class="text-muted">{{recipe.date.strftime('%d-%m-%Y')}}</small>
              </div>
            </div>
          </div>
        </div>
      <!-- End of single recipe-->
        {% endfor %}
{% endblock %}